### ISSUE TITLE
 Add an extended description of the connection

### ISSUE THREAD

**Issue by leonidkuznetsov18** [ElekenAgency/react-native-touch-id-android#3]
1 - android/build.gradle:

allprojects {
    repositories {

        ...
        maven { url "https://jitpack.io" } // <--- add this line
    }
}

2 - android/app/src/main/java/<YOUR-APP-FOLDER>/MainApplication file:
import com.smixx.fabric.FabricPackage;
import com.github.ajalt.reprint.core.Reprint;
and
public void onCreate() {
    super.onCreate();
    Reprint.initialize(this); // <- add this line
  }
and 
return Arrays.<ReactPackage>asList(
....
....
new FingerprintPackage()
)

**Comment by Vasiliev90** [comment]
done
