### ISSUE TITLE
Receiving error that co.eleken.react_native_touch_id_android does not exist

### ISSUE THREAD

**Issue by JSArrakis** [ElekenAgency/react-native-touch-id-android#4]
Hello,

Im attempting to build my application for the first time after completing the steps needed to include your package. I have followed your set up instructions to the letter and have not been able to build due to that error. Any assistance would be appreciated.

Thanks!

**Comment by Vasiliev90** [comment]
I've extended README instructions, try one more time to link the package, I guess the issue is in it

**Comment by Vasiliev90** [comment]
close issue due to inactivity
