### ISSUE TITLE
Not showing user prompt

### ISSUE THREAD

**Issue by JakeDawkins** [ElekenAgency/react-native-touch-id-android#6]
I'm not sure this is an issue. it's more of a question. Does Android have a default prompt to ask a user to scan fingerprints or would I need to wire one up? I saw the screenshot in your readme, but whenever I call the `requestTouch` method, I'm not seeing the prompt. 

It is, however, waiting for a fingerprint. If I auth with telnet (I'm on an emulator), the requestTouch method returns true. 

Thanks in advance!

**Comment by Vasiliev90** [comment]
@JakeDawkins , we needed a module without any visual prompts for our task so we created this module without any visual effects. Prompt on screenshot was created for the example and screenshot. You can create your own or get ours in example folder if you need it

**Comment by JakeDawkins** [comment]
Great! Thanks for the insight 👍
