### ISSUE TITLE
FingerprintPackage is broken after React Native 0.47

### ISSUE THREAD

**Issue by bit-sun** [ElekenAgency/react-native-touch-id-android#7]
Hi Vasiliev90,

In React Native 0.47, facebook removed createJSModules method from com.facebook.react.ReactPackage interface. As a result, you have to remove this method from your FingerprintPackage class, too. Could you please update your code? Thanks.

**Comment by Vasiliev90** [comment]
hi @bit-sun, yeah, I will do this in a few days. If you want and can create a PR, you are welcome.
